#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# NODEJS DOWNLOAD AND BUILD
#=================================================
ynh_script_progression "Installing NodeJS and its dependencies..."

pushd $install_dir
    ynh_hide_warnings ynh_exec_as_app npm install
    
    ynh_script_progression "Building $app..."
    ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
